### PR TITLE
Use new Enzyme mode `ReverseWithPrimal`

### PR DESCRIPTION
**Pull request by devmotion**
Was added in https://github.com/EnzymeAD/Enzyme.jl/pull/598.

### CODE REVIEW

**Comment by devmotion** [comment]
Ah, seems we have to wait. It's on the master branch but not released yet.

**Comment by tpapp** [comment]
Closing and reopening to trigger CI.

**Comment by devmotion** [comment]
Enzyme 0.11 not released yet, I think.

**Comment by tpapp** [comment]
Missed that, thanks. @vchuravy, would you please release current `master` of Enzyme so we can merge this?

**Comment by vchuravy** [comment]
Hopefully within a week or two, we want to make sure that all the API changes are sound and that split mode landed

**Comment by wsmoses** [comment]
Enzyme v0.11 has been released, so you should be able to update/merge this

**Review by tpapp — APPROVED** [review]
LGTM, thanks!

**Comment by tpapp** [comment]
CI failure is for Zygote and seems unrelated, merging, will tag a release.

**Pull request merged**
